"""Made shelves optional for books. They should not need a shelf to exist.

Revision ID: 01a21cfcf0f2
Revises: eb28a457773d
Create Date: 2026-04-09 12:48:11.948723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a21cfcf0f2'
down_revision: Union[str, Sequence[str], None] = 'eb28a457773d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_books', 'shelf_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_books', 'shelf_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
