"""Added book title and author to vector column for improved search.

Revision ID: 08c9aa53b35f
Revises: fb3f707d1c6c
Create Date: 2026-04-09 08:35:39.824496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c9aa53b35f'
down_revision: Union[str, Sequence[str], None] = 'fb3f707d1c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
