"""Added type to tags for filtration, added timestamp columns for soft delete/tracking

Revision ID: 12fe02f7b87e
Revises: 613b2c8bbd56
Create Date: 2026-04-08 13:28:57.236768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fe02f7b87e'
down_revision: Union[str, Sequence[str], None] = '613b2c8bbd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tags', sa.Column('type', sa.String(length=20), nullable=False))
    op.add_column('tags', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tags', sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tags', sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tags_type'), 'tags', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_type'), table_name='tags')
    op.drop_column('tags', 'deleted_on')
    op.drop_column('tags', 'updated_on')
    op.drop_column('tags', 'created_on')
    op.drop_column('tags', 'type')
    op.drop_column('entries', 'deleted_on')
    # ### end Alembic commands ###
