"""Added metadata dictionaries to book tags and note tags tables

Revision ID: 17b0f5fa16cc
Revises: 9eac10da8425
Create Date: 2026-04-03 06:33:35.558344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17b0f5fa16cc'
down_revision: Union[str, Sequence[str], None] = '9eac10da8425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_tags', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('note_tags', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_tags', 'meta_data')
    op.drop_column('book_tags', 'meta_data')
    # ### end Alembic commands ###
