"""Renamed the user book status column to user_status and mapped it properly with a default value

Revision ID: 20bfbf69060e
Revises: b669886108bd
Create Date: 2026-04-02 09:58:30.731957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bfbf69060e'
down_revision: Union[str, Sequence[str], None] = 'b669886108bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('reading_status', sa.String(length=15), nullable=False))
    op.add_column('user_books', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'added_at')
    op.drop_column('user_books', 'reading_status')
    # ### end Alembic commands ###
