"""Forgot to change mapped column to type 'str'

Revision ID: 279ffcfc19ed
Revises: 8aba5ad7a05a
Create Date: 2026-04-09 09:25:32.803170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279ffcfc19ed'
down_revision: Union[str, Sequence[str], None] = '8aba5ad7a05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_authors'), 'books', ['authors'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_authors'), table_name='books')
    # ### end Alembic commands ###
