"""Added custom title column to user books so user can fix their book's title from google api results

Revision ID: 29bb6bbe18b9
Revises: d85ed1a22a4a
Create Date: 2026-04-09 11:05:59.843064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bb6bbe18b9'
down_revision: Union[str, Sequence[str], None] = 'd85ed1a22a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('custom_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'custom_title')
    # ### end Alembic commands ###
