"""Created quote table. Added relationships to journal and user tables.

Revision ID: 2c374c488932
Revises: 665c7628c598
Create Date: 2026-03-31 23:15:40.449510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c374c488932'
down_revision: Union[str, Sequence[str], None] = '665c7628c598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_book_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('character', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_book_id'], ['user_books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('journals', sa.Column('quote_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'journals', 'quotes', ['quote_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journals', type_='foreignkey')
    op.drop_column('journals', 'quote_id')
    op.drop_table('quotes')
    # ### end Alembic commands ###
