"""Made the page count column for books nullable in case the google api doesn't have it

Revision ID: 3282a2bd87e7
Revises: 78cfaf796b68
Create Date: 2026-04-01 06:32:10.910215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3282a2bd87e7'
down_revision: Union[str, Sequence[str], None] = '78cfaf796b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
