"""Added chapter column to entries. Added indexes for userbook/page and userbook/chapter

Revision ID: 3a7750ce29d3
Revises: ef4242621e7c
Create Date: 2026-04-07 09:09:14.048126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7750ce29d3'
down_revision: Union[str, Sequence[str], None] = 'ef4242621e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('chapter', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_entries_chapter'), 'entries', ['chapter'], unique=False)
    op.create_index('ix_entries_user_book_chapter', 'entries', ['user_book_id', 'chapter'], unique=False)
    op.create_index('ix_entries_user_book_page', 'entries', ['user_book_id', 'page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_user_book_page', table_name='entries')
    op.drop_index('ix_entries_user_book_chapter', table_name='entries')
    op.drop_index(op.f('ix_entries_chapter'), table_name='entries')
    op.drop_column('entries', 'chapter')
    # ### end Alembic commands ###
