"""Updated all timestamp columsn to end in _at, because they represent a specific time, not a date.

Revision ID: 58b5d1ee6696
Revises: 12fe02f7b87e
Create Date: 2026-04-08 13:30:53.000658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58b5d1ee6696'
down_revision: Union[str, Sequence[str], None] = '12fe02f7b87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_clubs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('book_clubs', 'created_on')
    op.add_column('books', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.drop_column('books', 'updated_on')
    op.add_column('entries', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('entries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('entry_created_on'), 'entries', type_='unique')
    op.create_unique_constraint('entry_created_on', 'entries', ['user_book_id', 'created_at'])
    op.drop_column('entries', 'created_on')
    op.drop_column('entries', 'deleted_on')
    op.drop_column('entries', 'updated_on')
    op.add_column('tags', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tags', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tags', 'created_on')
    op.drop_column('tags', 'deleted_on')
    op.drop_column('tags', 'updated_on')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('users', 'updated_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.add_column('tags', sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tags', sa.Column('deleted_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tags', sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('tags', 'deleted_at')
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.add_column('entries', sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('entries', sa.Column('deleted_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('entries', sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('entry_created_on', 'entries', type_='unique')
    op.create_unique_constraint(op.f('entry_created_on'), 'entries', ['user_book_id', 'created_on'], postgresql_nulls_not_distinct=False)
    op.drop_column('entries', 'deleted_at')
    op.drop_column('entries', 'updated_at')
    op.drop_column('entries', 'created_at')
    op.add_column('books', sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('books', 'updated_at')
    op.add_column('book_clubs', sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('book_clubs', 'created_at')
    # ### end Alembic commands ###
