"""Added cascade deletions to the database

Revision ID: 613b2c8bbd56
Revises: 3a7750ce29d3
Create Date: 2026-04-08 08:35:05.976499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613b2c8bbd56'
down_revision: Union[str, Sequence[str], None] = '3a7750ce29d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_cases_user_id_fkey'), 'book_cases', type_='foreignkey')
    op.create_foreign_key(None, 'book_cases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('book_tags_user_book_id_fkey'), 'book_tags', type_='foreignkey')
    op.drop_constraint(op.f('book_tags_tag_id_fkey'), 'book_tags', type_='foreignkey')
    op.create_foreign_key(None, 'book_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_tags', 'user_books', ['user_book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('club_members_club_id_fkey'), 'club_members', type_='foreignkey')
    op.create_foreign_key(None, 'club_members', 'book_clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('entries_user_book_id_fkey'), 'entries', type_='foreignkey')
    op.create_foreign_key(None, 'entries', 'user_books', ['user_book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('entry_tags_tag_id_fkey'), 'entry_tags', type_='foreignkey')
    op.drop_constraint(op.f('entry_tags_entry_id_fkey'), 'entry_tags', type_='foreignkey')
    op.create_foreign_key(None, 'entry_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'entry_tags', 'entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('shelves_bookcase_id_fkey'), 'shelves', type_='foreignkey')
    op.create_foreign_key(None, 'shelves', 'book_cases', ['bookcase_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_books_user_id_fkey'), 'user_books', type_='foreignkey')
    op.create_foreign_key(None, 'user_books', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_books', type_='foreignkey')
    op.create_foreign_key(op.f('user_books_user_id_fkey'), 'user_books', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'shelves', type_='foreignkey')
    op.create_foreign_key(op.f('shelves_bookcase_id_fkey'), 'shelves', 'book_cases', ['bookcase_id'], ['id'])
    op.drop_constraint(None, 'entry_tags', type_='foreignkey')
    op.drop_constraint(None, 'entry_tags', type_='foreignkey')
    op.create_foreign_key(op.f('entry_tags_entry_id_fkey'), 'entry_tags', 'entries', ['entry_id'], ['id'])
    op.create_foreign_key(op.f('entry_tags_tag_id_fkey'), 'entry_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_foreign_key(op.f('entries_user_book_id_fkey'), 'entries', 'user_books', ['user_book_id'], ['id'])
    op.drop_constraint(None, 'club_members', type_='foreignkey')
    op.create_foreign_key(op.f('club_members_club_id_fkey'), 'club_members', 'book_clubs', ['club_id'], ['id'])
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.create_foreign_key(op.f('book_tags_tag_id_fkey'), 'book_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('book_tags_user_book_id_fkey'), 'book_tags', 'user_books', ['user_book_id'], ['id'])
    op.drop_constraint(None, 'book_cases', type_='foreignkey')
    op.create_foreign_key(op.f('book_cases_user_id_fkey'), 'book_cases', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
