"""Removed credentials table. Going for flat auth pattern

Revision ID: 665c7628c598
Revises: e819136e4778
Create Date: 2026-03-31 21:46:55.930817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665c7628c598'
down_revision: Union[str, Sequence[str], None] = 'e819136e4778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_email'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_is_active'), table_name='credentials')
    op.drop_table('credentials')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('apple_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['apple_id'])
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'apple_id')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'password_hash')
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credentials_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credentials_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('credentials_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_credentials_is_active'), 'credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_credentials_email'), 'credentials', ['email'], unique=True)
    # ### end Alembic commands ###
