"""gave primary key to note tags, foreign keys are now just foreign keys. Added unique constraint to note tags table

Revision ID: 738b2e7b3a70
Revises: 3acc3ea29861
Create Date: 2026-04-03 10:38:56.269412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738b2e7b3a70'
down_revision: Union[str, Sequence[str], None] = '3acc3ea29861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_tags', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_unique_constraint('_user_note_tag_uc', 'note_tags', ['note_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_note_tag_uc', 'note_tags', type_='unique')
    op.drop_column('note_tags', 'id')
    # ### end Alembic commands ###
