"""Made character and page count optional in the quotes table

Revision ID: 78cfaf796b68
Revises: 2c374c488932
Create Date: 2026-04-01 06:28:42.422949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cfaf796b68'
down_revision: Union[str, Sequence[str], None] = '2c374c488932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'character',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('quotes', 'page',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'page',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quotes', 'character',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
