"""Fixed typo in timestamp column for columns

Revision ID: 7b58fce9acb5
Revises: ed1cca8c8440
Create Date: 2026-04-08 13:43:21.610167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b58fce9acb5'
down_revision: Union[str, Sequence[str], None] = 'ed1cca8c8440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
