"""Added weights to ts vector so I can rank search results.

Revision ID: 8aba5ad7a05a
Revises: 08c9aa53b35f
Create Date: 2026-04-09 08:40:59.936636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8aba5ad7a05a'
down_revision: Union[str, Sequence[str], None] = '08c9aa53b35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 2. Add it back with the new multi-column logic
    # We use 'USING array_to_string(authors, ', ')' to preserve data
    op.execute("DROP INDEX IF EXISTS ix_books_ts_vector")
    # This removes the computed dependency so we can change 'authors'
    #op.drop_column('books', 'ts_vector')
    op.drop_index('ix_book_authors', table_name='books', postgresql_using='gin')
    op.alter_column('books', 'authors',
               type_=sa.Text(),
               existing_type=postgresql.ARRAY(sa.Text()),
               postgresql_using="array_to_string(authors, ', ')")
    op.add_column('books', 
            sa.Column('ts_vector', postgresql.TSVECTOR(), sa.Computed(
                "setweight(to_tsvector('english'::regconfig, coalesce(title, '')), 'A') || "
                "setweight(to_tsvector('english'::regconfig, coalesce(authors, '')), 'B') || "
                "setweight(to_tsvector('english'::regconfig, coalesce(description, '')), 'C')", 
                persisted=True
            ), nullable=False)
    )
    op.create_index('ix_tx_vector', 'books', ['ts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We use 'string_to_array' to reverse the process
    op.alter_column('books', 'authors',
               type_=postgresql.ARRAY(sa.Text()),
               existing_type=sa.Text(),
               postgresql_using="string_to_array(authors, ', ')")
    op.drop_index('ix_tx_vector', table_name='books', postgresql_using='gin')
    op.drop_column('books', 'ts_vector')
    # Restore the old single-column version
    op.add_column('books', 
        sa.Column('ts_vector', postgresql.TSVECTOR(), sa.Computed(
            "to_tsvector('english', coalesce(description, ''))", 
            persisted=True
        ), nullable=False)
    )

    op.create_index(op.f('ix_book_description'), 'books', ['ts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
