"""Made journals and quotes independent of each other

Revision ID: 9c8cb29a11fb
Revises: 3282a2bd87e7
Create Date: 2026-04-01 07:34:40.666236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8cb29a11fb'
down_revision: Union[str, Sequence[str], None] = '3282a2bd87e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('journals_quote_id_fkey'), 'journals', type_='foreignkey')
    op.drop_column('journals', 'quote_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('quote_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('journals_quote_id_fkey'), 'journals', 'quotes', ['quote_id'], ['id'])
    # ### end Alembic commands ###
