"""Added reading progress and vibe to journal entries. Added ability for them to be made public or private. Added status and renamed reading_progress to current_page

Revision ID: b669886108bd
Revises: 9c8cb29a11fb
Create Date: 2026-04-01 13:55:15.844393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b669886108bd'
down_revision: Union[str, Sequence[str], None] = '9c8cb29a11fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('journals', sa.Column('reading_progress', sa.Float(), nullable=False))
    op.add_column('journals', sa.Column('vibe', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('characters', sa.ARRAY(sa.String()), nullable=True))
    op.create_index('ix_quotes_characters_gin', 'quotes', ['characters'], unique=False, postgresql_using='gin')
    op.drop_column('quotes', 'character')
    op.add_column('user_books', sa.Column('current_page', sa.Integer(), nullable=False))
    op.drop_column('user_books', 'reading_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('reading_progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_books', 'current_page')
    op.add_column('quotes', sa.Column('character', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index('ix_quotes_characters_gin', table_name='quotes', postgresql_using='gin')
    op.drop_column('quotes', 'characters')
    op.drop_column('journals', 'vibe')
    op.drop_column('journals', 'reading_progress')
    op.drop_column('journals', 'is_private')
    # ### end Alembic commands ###
