"""Made authors a GIN index for books again

Revision ID: ca6abea7eeba
Revises: 3a385bb9582a
Create Date: 2026-04-09 19:28:49.319202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6abea7eeba'
down_revision: Union[str, Sequence[str], None] = '3a385bb9582a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_books_authors'), table_name='books')
    op.create_index('ix_book_authors', 'books', ['authors'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_authors', table_name='books', postgresql_using='gin')
    op.create_index(op.f('ix_books_authors'), 'books', ['authors'], unique=False)
    op.alter_column('books', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
