"""Made rating on book tags optional to reduce user friction.

Revision ID: d80c4c5dc09b
Revises: ea93dde02bbd
Create Date: 2026-04-03 11:52:01.890165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80c4c5dc09b'
down_revision: Union[str, Sequence[str], None] = 'ea93dde02bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_tags', 'rating_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_tags', 'rating_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
