"""Removed id for club_members because it's purely a linking table

Revision ID: d85ed1a22a4a
Revises: 279ffcfc19ed
Create Date: 2026-04-09 09:36:54.954292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85ed1a22a4a'
down_revision: Union[str, Sequence[str], None] = '279ffcfc19ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_members', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_members', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
