"""Removed spice rating from user book table. That will be handled with book tags

Revision ID: ea93dde02bbd
Revises: 738b2e7b3a70
Create Date: 2026-04-03 11:40:43.202485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea93dde02bbd'
down_revision: Union[str, Sequence[str], None] = '738b2e7b3a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('notes_trope_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.drop_column('notes', 'trope_id')
    op.drop_column('user_books', 'spice_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('spice_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('trope_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_trope_id_fkey'), 'notes', 'tags', ['trope_id'], ['id'])
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
