"""Fixed user timestamp column. Added search vector to user books

Revision ID: eb28a457773d
Revises: 29bb6bbe18b9
Create Date: 2026-04-09 12:12:58.302652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb28a457773d'
down_revision: Union[str, Sequence[str], None] = '29bb6bbe18b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', custom_title)", persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'search_vector')
    # ### end Alembic commands ###
