"""Made all timestamps have a server_default, except for deletion timestamps. Fixed timestamp for entries.

Revision ID: ed1cca8c8440
Revises: 58b5d1ee6696
Create Date: 2026-04-08 13:40:30.995015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed1cca8c8440'
down_revision: Union[str, Sequence[str], None] = '58b5d1ee6696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_clubs', sa.Column('Created_at', sa.DateTime(timezone=True), nullable=False, server_server_default=sa.text('now()')))
    op.drop_column('book_clubs', 'created_at')
    op.alter_column('entries', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('book_clubs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('book_clubs', 'Created_at')
    # ### end Alembic commands ###
