"""Renamed page_number column in entries table to page.

Revision ID: ef4242621e7c
Revises: 27919e0f866b
Create Date: 2026-04-07 08:49:01.102267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4242621e7c'
down_revision: Union[str, Sequence[str], None] = '27919e0f866b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('page', sa.Integer(), nullable=True))
    op.drop_column('entries', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'page')
    # ### end Alembic commands ###
