"""Replaced completed at column with deleted at so user books can be soft deleted.

Revision ID: f7daa390be35
Revises: d80c4c5dc09b
Create Date: 2026-04-03 20:11:21.223991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7daa390be35'
down_revision: Union[str, Sequence[str], None] = 'd80c4c5dc09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_tags', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('book_tags', 'rating_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('_user_book_tag_uc', 'book_tags', ['user_book_id', 'tag_id'])
    op.add_column('note_tags', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_unique_constraint('_user_note_tag_uc', 'note_tags', ['note_id', 'tag_id'])
    op.add_column('notes', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('notes_trope_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.drop_column('notes', 'trope_id')
    op.add_column('user_books', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_books', 'spice_rating')
    op.drop_column('user_books', 'date_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('date_completed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_books', sa.Column('spice_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_books', 'deleted_at')
    op.add_column('notes', sa.Column('trope_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_trope_id_fkey'), 'notes', 'tags', ['trope_id'], ['id'])
    op.drop_column('notes', 'user_id')
    op.drop_constraint('_user_note_tag_uc', 'note_tags', type_='unique')
    op.drop_column('note_tags', 'id')
    op.drop_constraint('_user_book_tag_uc', 'book_tags', type_='unique')
    op.alter_column('book_tags', 'rating_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('book_tags', 'id')
    # ### end Alembic commands ###
