"""Added overall rating to user books. This will help with filtration and book recommendations

Revision ID: fb3f707d1c6c
Revises: 7b58fce9acb5
Create Date: 2026-04-09 08:17:57.518328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3f707d1c6c'
down_revision: Union[str, Sequence[str], None] = '7b58fce9acb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_clubs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('book_clubs', 'favorite_book',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('book_clubs', 'Created_at')
    op.add_column('user_books', sa.Column('overall_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'overall_rating')
    op.add_column('book_clubs', sa.Column('Created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('book_clubs', 'favorite_book',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('book_clubs', 'created_at')
    # ### end Alembic commands ###
