"""Added bookcases and shelves tables. Added shelf id to userbook table.

Revision ID: fb3f1fce0534
Revises: 7ba35769f5be
Create Date: 2026-04-05 16:39:28.042946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3f1fce0534'
down_revision: Union[str, Sequence[str], None] = '7ba35769f5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookcases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bookcase_id', sa.Uuid(), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookcase_id'], ['bookcases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('entry_created_on', 'entries', ['user_book_id', 'created_on'])
    op.add_column('user_books', sa.Column('shelf_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_books', 'shelves', ['shelf_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_books', type_='foreignkey')
    op.drop_column('user_books', 'shelf_id')
    op.drop_constraint('entry_created_on', 'entries', type_='unique')
    op.drop_table('shelves')
    op.drop_table('bookcases')
    # ### end Alembic commands ###
