"""Added notes table, genres table, tropes table, and note_tropes table(link table). Added foreign keys to each and to user books table. Added relationships to user books and users table.

Revision ID: fc151da23117
Revises: 6d6c117aa59b
Create Date: 2026-04-02 11:14:05.823471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc151da23117'
down_revision: Union[str, Sequence[str], None] = '6d6c117aa59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_type', sa.String(), nullable=False),
    sa.Column('label_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tropes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_tropes',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('trope_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['trope_id'], ['tropes.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'trope_id')
    )
    op.add_column('notes', sa.Column('trope_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'notes', 'tropes', ['trope_id'], ['id'])
    op.add_column('user_books', sa.Column('genre_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_books', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_books', type_='foreignkey')
    op.drop_column('user_books', 'genre_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'trope_id')
    op.drop_table('note_tropes')
    op.drop_table('tropes')
    op.drop_table('genres')
    # ### end Alembic commands ###
